services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  chronicle:
    image: cratis/chronicle:latest
    ports:
      - "8080:8080"
    environment:
      MongoDB__ConnectionString: "mongodb://root:example@mongodb:27017"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
